// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/coderYarn/Desktop/perfect-map/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.14_ufuoz4donj5eabuiultxgjdaaq/node_modules/dumi/theme-default/slots/Footer/index.js';
