// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/coderYarn/Desktop/perfect-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.14_pi5pgkhimjhfbcyobqmxgtpunm/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
