// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/ApiLoader/index":{"id":"components/ApiLoader/index","path":"components/api-loader","parentId":"DocLayout"},"components/Map/index":{"id":"components/Map/index","path":"components/map","parentId":"DocLayout"},"components/Marker/index":{"id":"components/Marker/index","path":"components/marker","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.14_ufuoz4donj5eabuiultxgjdaaq__node_modules__dumi__dist__client__pages__404" */'C:/Users/EDY/Desktop/perfect-map/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.14_ufuoz4donj5eabuiultxgjdaaq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'C:/Users/EDY/Desktop/perfect-map/.dumi/tmp-production/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.14_ufuoz4donj5eabuiultxgjdaaq__node_modules__dumi__theme-default__layouts__DocLayout__index" */'C:/Users/EDY/Desktop/perfect-map/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.14_ufuoz4donj5eabuiultxgjdaaq/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'C:/Users/EDY/Desktop/perfect-map/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/EDY/Desktop/perfect-map/docs/index.md')),
'components/ApiLoader/index': React.lazy(() => import(/* webpackChunkName: "packages__perfect-map__src__components__ApiLoader__index.md" */'C:/Users/EDY/Desktop/perfect-map/packages/perfect-map/src/components/ApiLoader/index.md')),
'components/Map/index': React.lazy(() => import(/* webpackChunkName: "packages__perfect-map__src__components__Map__index.md" */'C:/Users/EDY/Desktop/perfect-map/packages/perfect-map/src/components/Map/index.md')),
'components/Marker/index': React.lazy(() => import(/* webpackChunkName: "packages__perfect-map__src__components__Marker__index.md" */'C:/Users/EDY/Desktop/perfect-map/packages/perfect-map/src/components/Marker/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.14_ufuoz4donj5eabuiultxgjdaaq__node_modules__dumi__dist__client__pages__Demo__index" */'C:/Users/EDY/Desktop/perfect-map/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.14_ufuoz4donj5eabuiultxgjdaaq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
